### ISSUE TITLE
"grid" "grid-cols-" "gap-" is not working in svelte preview after build

### ISSUE THREAD

**Issue by moisesbites** [windicss/svelte-windicss-preprocess#171]
Hello,

I'm testing a system in a remote server, and when I use in `npm run build`and `npm run preview`, the taildwindcss/windicss classes are not working: `grid` `grid-cols-?` `col-span-?` `gap-?`. it think that windi preprocessor of svelte is not compiling those classes.

Please, see image below:

![image](https://user-images.githubusercontent.com/8934577/122300749-bbd75100-cecd-11eb-9175-d8068810175d.png)

**Comment by alexanderniebuhr** [comment]
First things first. We need to confirm that the classes are not compiled. Please look in your Browsers Stylesheet and see if the classes are not compiled.

![image](https://user-images.githubusercontent.com/45965090/122342925-7191b680-cf45-11eb-8d88-c3c93177de3b.png)

If the classes are not compiled in that Style Editor, please share an svelte file with that classes used. However if the styles are inside that style editor, we need to find the issue why they are not used by browser.

**Comment by moisesbites** [comment]
Ok. Thank you @alexanderniebuhr .

I check the style editor, I made some changes in the code, I tested again and I think I found the problem: the classes in the inline class field in html tag are not compiling, but the classes in style tag are compiling.

For example:
```javascript

<-- those classes was not compiled -->
<div class="grid grid-cols-3 gap-2">
......
</div>

<!-- those classes was compiled  -->
<div class="main-fields">
.......
</div>

<style>
  .main-fields {
    @apply grid grid-cols-2 gap-2;
  }

  .address-fields {
    @apply grid grid-cols-10 gap-x-2;
  }
</style> 

 
![image](https://user-images.githubusercontent.com/8934577/122400566-d64f1000-cf49-11eb-8fcf-96af4f3a35e4.png)
![image](https://user-images.githubusercontent.com/8934577/122401100-4cec0d80-cf4a-11eb-90ff-2555652c646a.png)

For example, in the `svelte-kit/output/assets`, the css file has those classes like that:
```css
.main-fields.svelte-1h7fxln{display:-ms-grid;display:grid;grid-gap:.5rem;gap:.5rem;grid-template-columns:repeat(2,minmax(0,1fr))}.address-fields.svelte-1h7fxln{display:-ms-grid;display:grid;-webkit-column-gap:.5rem;-moz-column-gap:.5rem;grid-column-gap:.5rem;column-gap:.5rem;grid-template-columns:repeat(10,minmax(0,1fr))}
```

I hope to be helping to resolve this.

**Comment by alexanderniebuhr** [comment]
@moisesbites I just tested it with base setup and it works even inline. So I am thinking that this is some svelteKit specific issue with `npm run build`

**Comment by moisesbites** [comment]
OK. Thanks. Knowing that it works with style tags, I will change the code. What is your suggestion for this case? Maybe I should open an Issue in the sveltekit project related to this one?

**Comment by alexanderniebuhr** [comment]
[v4.0.9](https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v4.0.9) should fix this. No need to change your code to use style tags.

notes: svelteKit loads files with vite in parallel and we did not had an logic to safe styles for multiple files in memory. So in the end it has always used the styles of the last file (which is some svelteKit error page, which does not have any windicss styles at all, so empty style array is written). I have no idea why this only happens in production build and not development build, but it seems that this is the case, and maybe caused by some performance stuff they are doing.
No need to open an Issue on svelteKit Project, since I think this is the indented behavior by them.. even if I don't like it.

**Comment by alexanderniebuhr** [comment]
673ec6edd346d349ad12eec44ed3d4f6c38f3908
